## Import required pakages

In [1]:
import pandas as pd

## Load the dataset

In [3]:
df = pd.read_csv('data/raw_data.csv')
df.head()

,title,store,rating,number_of_ratings,price,color,size,brand,model,network,OS,cellular
0,"Samsung Galaxy M14 5G (ICY Silver, 6GB, 128GB ...",Visit the Samsung Store,3.9 out of 5 stars,"5,545 ratings","15,790.",Icy Silver,6GB + 128GB,Samsung,Samsung Galaxy M14 5G,Unlocked for All Carriers,Android 13.0,5G
1,"Samsung Galaxy S23 5G (Green, 8GB, 128GB Storage)",Visit the Samsung Store,4.5 out of 5 stars,698 ratings,"74,998.",NaN,NaN,Samsung,Samsung Galaxy S23,Unlocked for All Carriers,Android 13.0,5G
2,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...",Visit the OnePlus Store,4.2 out of 5 stars,"130,427 ratings","17,999.",Black Dusk,"6GB RAM, 128GB Storage",OnePlus,OnePlus Nord CE 2 Lite 5G,Unlocked for All Carriers,OxygenOS,5G
3,"Redmi A2 (Aqua Blue, 2GB RAM, 32GB Storage) | ...",Brand: Redmi,3.7 out of 5 stars,"1,875 ratings","6,499.",Aqua Blue,NaN,Redmi,Redmi A2,Unlocked for All Carriers,"Android 13 Go, Android 13.0",4G
4,"Samsung Galaxy M13 (Midnight Blue, 6GB, 128GB ...",Visit the Samsung Store,4.1 out of 5 stars,"25,408 ratings","11,649.",NaN,NaN,Samsung,Samsung Galaxy M13,Unlocked for All Carriers,Android 12.0,4G

### Clean title row

In [24]:
product = []
for data_num in range(len(df['title'])):
    data_lis = df['title'][data_num].split('(')
    product.append(data_lis[0])
    if len(data_lis[0])>40:
        print(data_lis[0],data_num)

product[5] = "Samsung Galaxy M04"
product[27] = "Nokia C22"
product[36] = "Nokia 2660"
print(product) 

df["product"] = pd.Series(product)

Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 Octa-core Processor | 5000 mAh Battery | 13MP Dual Camera 5
Nokia C22 | 3-Day Battery Life | 6GB RAM  27
Nokia 2660 Flip 4G Volte keypad Phone with Dual SIM, Dual Screen, inbuilt MP3 Player & Wireless FM Radio | Black 36
['Samsung Galaxy M14 5G ', 'Samsung Galaxy S23 5G ', 'OnePlus Nord CE 2 Lite 5G ', 'Redmi A2 ', 'Samsung Galaxy M13 ', 'Samsung Galaxy M04', 'iQOO Z6 Lite 5G ', 'Samsung Galaxy M13 ', 'Samsung Galaxy M32 Prime Edition ', 'Redmi 12C ', 'Itel A60s ', 'Itel P40+ ', 'iQOO Z7s 5G by vivo ', 'realme narzo 50i Prime ', 'Samsung Galaxy M13 ', 'realme narzo 50i ', 'Redmi 12C ', 'Oppo A78 5G ', 'realme narzo N55 ', 'Lava Blaze 5G ', 'Itel S23 ', 'Samsung Galaxy A34 5G ', 'IKALL S1 Smartphone ', 'Itel A60s ', 'Vivo Y27 ', 'Samsung Galaxy S20 FE 5G ', 'Lava Blaze 5G ', 'Nokia C22', 'realme narzo N55 ', 'OnePlus Nord CE 3 5G ', 'realme narzo N53 ', 'TECNO Spark 9 ', 'Samsung Galaxy M14 5G ', 'Itel P40+ ', 'Nokia C12 Android 12 ', 'OnePlus Nord CE 2 Lite 5G ', 'Nokia 2660', 'realme narzo N55 ', 'realme narzo N53 ', 'OnePlus Nord CE 3 Lite 5G ', 'OnePlus Nord CE 3 Lite 5G ', 'realme narzo 60 5G ', 'IKALL S1 Smartphone ', 'Samsung Galaxy S23 5G ']

In [25]:
df.head()

,title,store,rating,number_of_ratings,price,color,size,brand,model,network,OS,cellular,product
0,"Samsung Galaxy M14 5G (ICY Silver, 6GB, 128GB ...",Visit the Samsung Store,3.9 out of 5 stars,"5,545 ratings","15,790.",Icy Silver,6GB + 128GB,Samsung,Samsung Galaxy M14 5G,Unlocked for All Carriers,Android 13.0,5G,Samsung Galaxy M14 5G
1,"Samsung Galaxy S23 5G (Green, 8GB, 128GB Storage)",Visit the Samsung Store,4.5 out of 5 stars,698 ratings,"74,998.",NaN,NaN,Samsung,Samsung Galaxy S23,Unlocked for All Carriers,Android 13.0,5G,Samsung Galaxy S23 5G
2,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...",Visit the OnePlus Store,4.2 out of 5 stars,"130,427 ratings","17,999.",Black Dusk,"6GB RAM, 128GB Storage",OnePlus,OnePlus Nord CE 2 Lite 5G,Unlocked for All Carriers,OxygenOS,5G,OnePlus Nord CE 2 Lite 5G
3,"Redmi A2 (Aqua Blue, 2GB RAM, 32GB Storage) | ...",Brand: Redmi,3.7 out of 5 stars,"1,875 ratings","6,499.",Aqua Blue,NaN,Redmi,Redmi A2,Unlocked for All Carriers,"Android 13 Go, Android 13.0",4G,Redmi A2
4,"Samsung Galaxy M13 (Midnight Blue, 6GB, 128GB ...",Visit the Samsung Store,4.1 out of 5 stars,"25,408 ratings","11,649.",NaN,NaN,Samsung,Samsung Galaxy M13,Unlocked for All Carriers,Android 12.0,4G,Samsung Galaxy M13

### Clean store row

In [28]:
df['store'].value_counts()
for

store
Visit the Samsung Store    11
Visit the realme Store      8
Visit the OnePlus Store     5
Visit the Itel Store        5
Brand: Redmi                3
Visit the Nokia Store       3
Visit the iQOO Store        2
Visit the IKALL Store       2
Visit the Oppo Store        1
Brand: Lava                 1
Visit the Vivo Store        1
Visit the Lava Store        1
Visit the Tecno Store       1
Name: count, dtype: int64